### ISSUE TITLE
Individual Trash Buttons Per Pin

### ISSUE THREAD

**Issue by wryanj** [dassoumik/city411#33]
Add individual pin buttons on each pin for 1,1 delete

**Comment by Kyle7286** [comment]
Hey Ryan - I accomplished this in my JS for each ticket master event and looks like the below.
I think you dont have to worry about it unless you want the logic to create that; it is simply a font awesome icon but you give it styling and a class of your choice.
![image](https://user-images.githubusercontent.com/74633494/106807659-62b20380-6637-11eb-8148-8f69f961ca6b.png)


![image](https://user-images.githubusercontent.com/74633494/106807371-11097900-6637-11eb-9902-2b0281c2ef11.png)

**Comment by wryanj** [comment]
@Kyle7286 looks good. I will add a little formatting to it, and will also add some little delete buttons on each pin (thats what I meant to say with this ticked my fault).

**Comment by wryanj** [comment]
This is awaiting review. Added a little delete button within each pin card as a template, so that users could delete the pin cards one by one if they wanted. THis was specific to the Pin cards generated after a user pins something
