### ISSUE TITLE
Ensure all elemenets that should be hidden when no city search are hidden

### ISSUE THREAD

**Issue by wryanj** [dassoumik/city411#37]

**Comment by wryanj** [comment]
![image](https://user-images.githubusercontent.com/72420733/106816572-91ce7200-6643-11eb-8600-df170861c25a.png)
![image](https://user-images.githubusercontent.com/72420733/106816678-bb879900-6643-11eb-8fde-aab6e0b4797c.png)

**Comment by Kyle7286** [comment]
This has been added and pushed for review.

**Comment by Kyle7286** [comment]
This bug was fixed in the latest deployment.
All the appropriate elements will be hidden upon the first hit of the page, then will unhide when you search a city.
