### ISSUE TITLE
[New Feature] [PIN] - Save Favorite Tiles

### ISSUE THREAD

**Issue by Kyle7286** [dassoumik/city411#39]
- It would be nice if users can save "tiles" of details so that they can come back to the app and resume. 
- This would be a great addition for users who want to keep POIs, restaurants, clubs, bars, etc...

**Comment by Kyle7286** [comment]
To provide an update on this:
1. Soumik added PIN logic for food.
2. Entertainment logic pinning was an extra feature not part of MVP due to time but is a future feature coming soon.
Side Note: It wouldnt be difficult at all to add that feature; just time is of the essence!

**Comment by dassoumik** [comment]
For entertainment section I requested the data that should be put on the pins, but did not receive it from Brandon.
The pin addition and deletion logic all is in place only entertainment event data need to gathered and displayed. 
Should be a small update.

**Comment by Kyle7286** [comment]
TicketMaster was not part of MVP and ran out of time. This will need to be an added feature post-deadline

**Comment by Kyle7286** [comment]
@dassoumik included the PIN logic for food tiles.
Event tiles will be in icebox.
