### ISSUE TITLE
[HTML] PIN Container Height Impacts Event Container Height

### ISSUE THREAD

**Issue by Kyle7286** [dassoumik/city411#47]

**Comment by Kyle7286** [comment]
The height of the pin container impact the events container's height, but it does not impact the food container:

![image](https://user-images.githubusercontent.com/74633494/106925458-1cfc4600-66de-11eb-8a2d-3c2b519ae9c6.png)

**Comment by dassoumik** [comment]
Need to work on this in future

**Comment by dassoumik** [comment]
if there are any issues

**Comment by dassoumik** [comment]
The pic in here looks an old styling. Closing this off.
