### ISSUE TITLE
[LOGIC] [BUG] Food Tiles Continue to Loop When Switching Cities

### ISSUE THREAD

**Issue by Kyle7286** [dassoumik/city411#49]
Food tiles continue to loop for previous city even though you switch to another city... each new city adds a loop and you can see the previous cities food

**Comment by Kyle7286** [comment]
To duplicate:

1. Search a city
2. Search another city
3. Search another city
4. Notice how the food tiles are continuing to loop over themselves constantly

Potential SOlution:
- Find a way to stop the previous loop and start a new one with a new data set

**Comment by Kyle7286** [comment]
Seems like this occurs if searching by favorites. Not an MVP issue; no stress

**Comment by dassoumik** [comment]
It was not a bug, the favorite option was later added and it was coded to initialize the food process. I have added that logic with my other updates.
