### ISSUE TITLE
[BUG] Favorite function not working. Please fix logic.

### ISSUE THREAD

**Issue by dassoumik** [dassoumik/city411#52]
Favorite function not working. Please fix logic.

**Comment by Kyle7286** [comment]
- This bug has been fixed in a local repo but awaiting discussion on when to push it up for prod.
- The issue was due to the listener not being created again after clicking a favorite.

**Comment by Kyle7286** [comment]
This bug was fixed with the final deployment last night.  Favorites are operational!
